language: go

go:
  - 1.11.x
  - 1.12.x
  - 1.13.x

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic github.com/cornelk/goscrape/scraper

after_success:
  - bash <(curl -s https://codecov.io/bash)
