[[constraint]]
  name = "github.com/PuerkitoBio/goquery"
  version = "1.5.0"

[[constraint]]
  name = "github.com/gorilla/css"
  version = "1.0.0"

[[constraint]]
  name = "github.com/headzoo/surf"
  version = "1.0.0"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.3"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.2.1"

[[constraint]]
  name = "go.uber.org/zap"
  version = "1.9.1"

[[constraint]]
  name = "gopkg.in/h2non/filetype.v1"
  version = "1.0.5"

[prune]
  go-tests = true
  unused-packages = true
